kind: Kustomization
apiVersion: kustomize.config.k8s.io/v1beta1

namespace: dara-metrics

configMapGenerator:
  - name: grafana-dashboard-dora-metrics
    files:
      - dashboards/dora-dashboard.json

resources:
  - dashboard.yaml