---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: exporter
  namespace: dora-metrics
spec:
  replicas: 1
  selector:
    matchLabels:
      app: exporter
  template:
    metadata:
      labels:
        app: exporter
    spec:
      containers:
        - name: container
          image: 'quay.io/redhat-appstudio/dora-metrics:68814cca4f0d767b11cceb4f2c6ea0220ed8d449'
          ports:
            - name: metrics-port
              containerPort: 9101
              protocol: TCP
          env:
            - name: GITHUB_TOKEN
              valueFrom:
                secretKeyRef:
                  name: exporters-secret
                  key: github
                  optional: false
            - name: PAGERDUTY_API_KEY
              valueFrom:
                secretKeyRef:
                  name: exporters-secret
                  key: pager-duty-token
                  optional: false
      serviceAccountName: dora-metrics-exporter-sa
      serviceAccount: dora-metrics-exporter-sa