apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- serviceaccount.yaml
- clusterrole.yaml
- clusterrolebinding.yaml
- configmap.yaml
- deployment.yaml
- service.yaml
- servicemonitor.yaml

images:
  - name: quay.io/redhat-appstudio/dora-metrics
    newName: quay.io/redhat-appstudio/dora-metrics
    newTag: 4ee139d33d2ddd8c73496b2a82975b46f22720a2